drop function if exists oxpl.fnc_hier_get_childs; /* 0001 */
drop function if exists oxpl.fnc_ccenter_map; /* 0002 */
drop function if exists oxpl.fnc_coarea_get_by_cod; /* 0003.01 */
drop function if exists oxpl.fnc_coarea_get_by_hier; /* 0003.02 */
drop procedure if exists oxpl.prc_coarea_insert_return; /* 0003.03 */
drop procedure if exists oxpl.prc_coarea_update_return; /* 0003.04 */
drop procedure if exists oxpl.prc_coarea_delete_return; /* 0003.05 */
drop procedure if exists oxpl.prc_coarea_get_list_all; /* 0003.06 */
drop procedure if exists oxpl.prc_coarea_get_list_alocare; /* 0003.07 */
drop procedure if exists oxpl.prc_coarea_get_list_by_ccntr_bound; /* 0003.08 */
drop procedure if exists oxpl.prc_coarea_get_list_by_ccntr_bound_alocare; /* 0003.09 */
drop procedure if exists oxpl.prc_coarea_get_list_by_cdriver_bound; /* 0003.10 */
drop function if exists oxpl.fnc_icpart_get_by_cod; /* 0004.01 */
drop procedure if exists oxpl.prc_icpart_insert_return; /* 0004.02 */
drop procedure if exists oxpl.prc_icpart_update_return; /* 0004.03 */
drop procedure if exists oxpl.prc_icpart_delete_return; /* 0004.04 */
drop procedure if exists oxpl.prc_icpart_get_list_all; /* 0004.05 */
drop procedure if exists oxpl.prc_icpart_get_list_not_refer_to_coarea; /* 0004.06 */
drop function if exists oxpl.fnc_segind_get_by_cod; /* 0005.01 */
drop procedure if exists oxpl.prc_segind_insert_return; /* 0005.02 */
drop procedure if exists oxpl.prc_segind_update_return; /* 0005.03 */
drop procedure if exists oxpl.prc_segind_delete_return; /* 0005.04 */
drop procedure if exists oxpl.prc_segind_get_list_all; /* 0005.05 */
drop function if exists oxpl.fnc_bussline_get_by_cod; /* 0006.01 */
drop procedure if exists oxpl.prc_bussline_insert_return; /* 0006.02 */
drop procedure if exists oxpl.prc_bussline_update_return; /* 0006.03 */
drop procedure if exists oxpl.prc_bussline_delete_return; /* 0006.04 */
drop procedure if exists oxpl.prc_bussline_get_list_all; /* 0006.05 */
drop procedure if exists oxpl.prc_bussline_get_list_not_asign_to_coarea; /* 0006.06 */
drop function if exists oxpl.fnc_bussasg_get_by_id; /* 0007.01 */
drop procedure if exists oxpl.prc_bussasg_insert_return; /* 0007.02 */
drop procedure if exists oxpl.prc_bussasg_delete_return; /* 0007.03 */
drop procedure if exists oxpl.prc_bussasg_get_list_asign_to_coarea; /* 0007.04 */
drop function if exists oxpl.fnc_month_get_by_cod; /* 0008.01 */
drop procedure if exists oxpl.prc_month_insert_return; /* 0008.02 */
drop procedure if exists oxpl.prc_month_update_return; /* 0008.03 */
drop procedure if exists oxpl.prc_month_delete_return; /* 0008.04 */
drop procedure if exists oxpl.prc_month_get_list_all; /* 0008.05 */
drop function if exists oxpl.fnc_planvers_get_by_cod; /* 0009.01 */
drop procedure if exists oxpl.prc_planvers_insert_return; /* 0009.02 */
drop procedure if exists oxpl.prc_planvers_update_return; /* 0009.03 */
drop procedure if exists oxpl.prc_planvers_delete_return; /* 0009.04 */
drop procedure if exists oxpl.prc_planvers_get_list_all; /* 0009.05 */
drop function if exists oxpl.fnc_dataset_get_by_id; /* 0010.01 */
drop procedure if exists oxpl.prc_dataset_insert_return; /* 0010.02 */
drop procedure if exists oxpl.prc_dataset_update_return; /* 0010.03 */
drop procedure if exists oxpl.prc_dataset_delete_return; /* 0010.04 */
drop procedure if exists oxpl.prc_dataset_get_list_ani; /* 0010.05 */
drop procedure if exists oxpl.prc_dataset_get_list_plan_ani; /* 0010.06 */
drop procedure if exists oxpl.prc_dataset_get_list_childs; /* 0010.07 */
drop procedure if exists oxpl.prc_dataset_has_values; /* 0010.08 */
drop procedure if exists oxpl.prc_dataset_no_of_periods; /* 0010.09 */
drop procedure if exists oxpl.prc_dataset_get_list_by_an; /* 0010.10 */
drop procedure if exists oxpl.prc_dataset_get_list_actual_not_incheiat; /* 0010.11 */
drop procedure if exists oxpl.prc_dataset_get_list_not_blocked; /* 0010.12 */
drop procedure if exists oxpl.prc_dataset_get_list_plan_by_an; /* 0010.13 */
drop procedure if exists oxpl.prc_dataset_get_list_plan_not_blocat; /* 0010.14 */
drop procedure if exists oxpl.prc_dataset_get_list_plan_not_incheiat; /* 0010.15 */
drop procedure if exists oxpl.prc_dataset_get_list_plan_not_incheiat_with_ref; /* 0010.16 */
drop procedure if exists oxpl.prc_dataset_get_list_plan_raportare_by_an; /* 0010.17 */
drop procedure if exists oxpl.prc_dataset_get_list_raportare_ani; /* 0010.18 */
drop procedure if exists oxpl.prc_dataset_get_list_raportare_all; /* 0010.19 */
drop function if exists oxpl.fnc_datasetper_get_by_id; /* 0011.01 */
drop procedure if exists oxpl.prc_datasetper_insert_return; /* 0011.02 */
drop procedure if exists oxpl.prc_datasetper_update_return; /* 0011.03 */
drop procedure if exists oxpl.prc_datasetper_delete_return; /* 0011.04 */
drop procedure if exists oxpl.prc_datasetper_delete_all_by_data_set; /* 0011.05 */
drop procedure if exists oxpl.prc_datasetper_take_over; /* 0011.06 */
drop procedure if exists oxpl.prc_datasetper_get_list_by_data_set; /* 0011.07 */
drop function if exists oxpl.fnc_costcentergroup_get_by_id; /* 0012.01 */
drop procedure if exists oxpl.prc_costcentergroup_insert_return; /* 0012.02 */
drop procedure if exists oxpl.prc_costcentergroup_update_return; /* 0012.03 */
drop procedure if exists oxpl.prc_costcentergroup_delete_return; /* 0012.04 */
drop procedure if exists oxpl.prc_costcentergroup_delete_by_hier_and_data_set; /* 0012.05 */
drop procedure if exists oxpl.prc_costcentergroup_take_over; /* 0012.06 */
drop procedure if exists oxpl.prc_costcentergroup_get_by_hier_data_set_and_cod; /* 0012.07 */
drop procedure if exists oxpl.prc_costcentergroup_get_list_by_hier_and_data_set; /* 0012.08 */
drop function if exists oxpl.fnc_costcenter_get_by_id; /* 0013.01 */
drop procedure if exists oxpl.prc_costcenter_insert_return; /* 0013.02 */
drop procedure if exists oxpl.prc_costcenter_update_return; /* 0013.03 */
drop procedure if exists oxpl.prc_costcenter_delete_return; /* 0013.04 */
drop procedure if exists oxpl.prc_costcenter_delete_all; /* 0013.05 */
drop procedure if exists oxpl.prc_costcenter_get_by_cod; /* 0013.06 */
drop procedure if exists oxpl.prc_costcenter_get_list_by_hier_and_data_set; /* 0013.07 */
drop procedure if exists oxpl.prc_costcenter_get_list_by_hier_data_set_and_rights; /* 0013.08 */
drop procedure if exists oxpl.prc_costcenter_take_over; /* 0013.09 */
drop function if exists oxpl.fnc_costdriver_get_by_cod; /* 0014.01 */
drop procedure if exists oxpl.prc_costdriver_insert_return; /* 0014.02 */
drop procedure if exists oxpl.prc_costdriver_update_return; /* 0014.03 */
drop procedure if exists oxpl.prc_costdriver_delete_return; /* 0014.04 */
drop procedure if exists oxpl.prc_costdriver_get_list_all; /* 0014.05 */
drop procedure if exists oxpl.prc_costdriver_get_list_by_central; /* 0014.06 */
drop function if exists oxpl.fnc_costdriver_asign_get_by_id; /* 0014.07 */
drop procedure if exists oxpl.prc_costdriver_asign_insert_return; /* 0014.08 */
drop procedure if exists oxpl.prc_costdriver_asign_update_return; /* 0014.09 */
drop procedure if exists oxpl.prc_costdriver_asign_delete_return; /* 0014.10 */
drop procedure if exists oxpl.prc_costdriver_asign_get_list_all; /* 0014.11 */
drop procedure if exists oxpl.prc_costdriver_asign_get_list_by_central; /* 0014.12 */
drop procedure if exists oxpl.prc_costdriver_asign_get_list_not_asign_to_coarea; /* 0014.13 */
drop procedure if exists oxpl.prc_costdriver_asign_get_list_by_rights; /* 0014.14 */
drop procedure if exists oxpl.prc_costdriver_asign_check_is_assigned; /* 0014.15 */
drop procedure if exists oxpl.prc_costdriver_asign_get_by_cod_and_coarea; /* 0014.16 */
drop function if exists oxpl.fnc_opexcateg_get_by_cod; /* 0015.01 */
drop procedure if exists oxpl.prc_opexcateg_insert_return; /* 0015.02 */
drop procedure if exists oxpl.prc_opexcateg_update_return; /* 0015.03 */
drop procedure if exists oxpl.prc_opexcateg_delete_return; /* 0015.04 */
drop procedure if exists oxpl.prc_opexcateg_get_list_all; /* 0015.05 */
drop procedure if exists oxpl.prc_opexcateg_get_list_by_cost_driver; /* 0015.06 */
drop function if exists oxpl.fnc_opexcateg_asign_get_by_id; /* 0015.07 */
drop procedure if exists oxpl.prc_opexcateg_asign_insert_return; /* 0015.08 */
drop procedure if exists oxpl.prc_opexcateg_asign_update_return; /* 0015.09 */
drop procedure if exists oxpl.prc_opexcateg_asign_delete_return; /* 0015.10 */
drop procedure if exists oxpl.prc_opexcateg_asign_get_list_by_coarea; /* 0015.11 */
drop procedure if exists oxpl.prc_opexcateg_asign_get_list_by_coarea_and_driver; /* 0015.12 */
drop procedure if exists oxpl.prc_opexcateg_asign_get_list_not_asign; /* 0015.13 */
drop procedure if exists oxpl.prc_opexcateg_asign_get_by_cod_and_coarea; /* 0015.14 */
drop procedure if exists oxpl.prc_user_group_get_all; /* 0016.01 */
drop procedure if exists oxpl.prc_user_group_get_specific_list; /* 0016.02 */
drop procedure if exists oxpl.prc_user_get_list_by_group; /* 0016.03 */
drop procedure if exists oxpl.prc_user_get_list_by_hier; /* 0016.04 */
drop procedure if exists oxpl.prc_user_add_rights_by_cost_center; /* 0016.05 */
drop procedure if exists oxpl.prc_user_del_rights_by_cost_center; /* 0016.06 */
drop procedure if exists oxpl.prc_user_get_list_by_cost_center; /* 0016.07 */
drop procedure if exists oxpl.prc_user_check_cost_center_bound; /* 0016.08 */
drop procedure if exists oxpl.prc_user_add_rights_by_cost_driver; /* 0016.09 */
drop procedure if exists oxpl.prc_user_del_rights_by_cost_driver; /* 0016.10 */
drop procedure if exists oxpl.prc_user_get_list_by_cost_driver; /* 0016.11 */
drop procedure if exists oxpl.prc_user_check_cost_driver_bound; /* 0016.12 */
drop procedure if exists oxpl.prc_user_group_get_by_cod; /* 0016.13 */
drop procedure if exists oxpl.prc_user_has_rights_on_ccenter; /* 0016.14 */
drop procedure if exists oxpl.prc_user_has_rights_on_cdriver; /* 0016.15 */
drop procedure if exists oxpl.prc_cheie_tip_get_list_all; /* 0017.01 */
drop procedure if exists oxpl.prc_cheie_get_list_asign_no_val; /* 0017.02 */
drop procedure if exists oxpl.prc_cheie_get_list_gen_def_all; /* 0017.03 */
drop procedure if exists oxpl.prc_cheie_get_val_by_id_and_ccenter; /* 0017.04 */
drop function if exists oxpl.fnc_cheie_s01_get_by_id; /* 0018.01 */
drop function if exists oxpl.fnc_cheie_s01_get_by_id_aggr; /* 0018.02 */
drop procedure if exists oxpl.prc_cheie_s01_insert_return; /* 0018.03 */
drop procedure if exists oxpl.prc_cheie_s01_update_return; /* 0018.04 */
drop procedure if exists oxpl.prc_cheie_s01_delete_return; /* 0018.05 */
drop procedure if exists oxpl.prc_cheie_s01_get_list_by_ccenter_with_an_total; /* 0018.06 */
drop procedure if exists oxpl.prc_cheie_s01_get_raw_data_by_ccenter; /* 0018.07 */
drop procedure if exists oxpl.prc_cheie_g01_def_insert_return; /* 0019.01 */
drop procedure if exists oxpl.prc_cheie_g01_def_update_return; /* 0019.02 */
drop procedure if exists oxpl.prc_cheie_g01_def_delete; /* 0019.03 */
drop procedure if exists oxpl.prc_cheie_g01_def_get_all; /* 0019.04 */
drop procedure if exists oxpl.prc_cheie_g01_val_maintain; /* 0019.05 */
drop procedure if exists oxpl.prc_cheie_g01_val_delete_by_cheie_and_set; /* 0019.06 */
drop procedure if exists oxpl.prc_cheie_g01_val_take_over_by_cheie; /* 0019.07 */
drop procedure if exists oxpl.prc_cheie_g01_val_get_by_cheie_and_ccenter; /* 0019.08 */
drop procedure if exists oxpl.prc_cheie_g01_val_get_by_cheie_and_set; /* 0019.09 */
drop procedure if exists oxpl.prc_cheie_g01_val_get_by_coarea_and_set; /* 0019.10 */
drop procedure if exists oxpl.prc_cheie_g01_val_get_grouped_by_hier_and_set; /* 0019.11 */
drop procedure if exists oxpl.prc_cheie_g01_def_get_by_id; /* 0019.12 */
drop procedure if exists oxpl.prc_cheie_g02_get_by_id; /* 0020.01 */
drop function if exists oxpl.fnc_cheie_g02_get_by_id_aggr; /* 0020.02 */
drop procedure if exists oxpl.prc_cheie_g02_insert_return; /* 0020.03 */
drop procedure if exists oxpl.prc_cheie_g02_update_return; /* 0020.04 */
drop procedure if exists oxpl.prc_cheie_g02_def_delete; /* 0020.05 */
drop procedure if exists oxpl.prc_cheie_g02_val_take_over_by_cheie; /* 0020.06 */
drop procedure if exists oxpl.prc_cheie_g02_get_list_all; /* 0020.07 */
drop procedure if exists oxpl.prc_cheie_g02_get_raw_data_by_set; /* 0020.08 */
drop procedure if exists oxpl.prc_cheie_c01_get_by_id; /* 0021.01 */
drop procedure if exists oxpl.prc_cheie_c01_def_insert_return; /* 0021.02 */
drop procedure if exists oxpl.prc_cheie_c01_def_update_return; /* 0021.03 */
drop procedure if exists oxpl.prc_cheie_c01_def_delete; /* 0021.04 */
drop procedure if exists oxpl.prc_cheie_c01_val_delete_by_key; /* 0021.05 */
drop procedure if exists oxpl.prc_cheie_c01_val_delete_by_coarea_and_set; /* 0021.06 */
drop procedure if exists oxpl.prc_cheie_c01_rule_get_by_key; /* 0021.07 */
drop procedure if exists oxpl.prc_cheie_c01_rule_insert_return; /* 0021.08 */
drop procedure if exists oxpl.prc_cheie_c01_rule_update_return; /* 0021.09 */
drop procedure if exists oxpl.prc_cheie_c01_rule_delete_return; /* 0021.10 */
drop procedure if exists oxpl.prc_cheie_c01_rule_check_val_exists; /* 0021.11 */
drop procedure if exists oxpl.prc_cheie_c01_check_val_exists; /* 0021.12 */
drop procedure if exists oxpl.prc_cheie_c01_calculate; /* 0021.13 */
drop procedure if exists oxpl.prc_cheie_c01_get_list_all; /* 0021.14 */
drop procedure if exists oxpl.prc_cheie_c01_get_raw_data_by_set; /* 0021.15 */
drop procedure if exists oxpl.prc_recs_actual_delete_by_id; /* 0022.01 */
drop procedure if exists oxpl.prc_recs_plan_delete_doc_by_id; /* 0023.01 */
drop procedure if exists oxpl.prc_recs_plan_delete_val_by_id; /* 0023.02 */
drop procedure if exists oxpl.prc_recs_plan_take_over_actuals; /* 0023.03 */
drop procedure if exists oxpl.prc_recs_plan_take_over_asign; /* 0023.04 */
drop procedure if exists oxpl.recs_plan_take_over_plan; /* 0023.05 */
drop procedure if exists oxpl.prc_costcentermap_insert_return; /* 0024.01 */
drop procedure if exists oxpl.prc_costcentermap_update_return; /* 0024.02 */
drop procedure if exists oxpl.prc_costcentermap_delete_by_id_return; /* 0024.03 */
drop procedure if exists oxpl.prc_costcentermap_delete_all_return; /* 0024.04 */
drop procedure if exists oxpl.prc_costcentermap_get_list_all_mapped; /* 0024.05 */
drop procedure if exists oxpl.prc_costcentermap_get_list_not_mapped; /* 0024.06 */
drop function if exists oxpl.fnc_plandoc_get_by_id; /* 0025.01 */
drop procedure if exists oxpl.prc_plandoc_insert_return; /* 0025.02 */
drop procedure if exists oxpl.prc_plandoc_update_return; /* 0025.03 */
drop procedure if exists oxpl.prc_plandoc_delete_return; /* 0024.04 */
drop procedure if exists oxpl.prc_plandoc_get_list_ccenter_ncentr_sumar; /* 0025.05 */
drop procedure if exists oxpl.prc_plandoc_get_raw_ccenter_ncentr_sumar; /* 0025.06 */
drop procedure if exists oxpl.prc_plandoc_get_list_ccenter_ncentr_pozitii; /* 0025.07 */
drop procedure if exists oxpl.prc_plandoc_get_raw_ccenter_ncentr_pozitii; /* 0025.08 */
drop procedure if exists oxpl.prc_plandoc_get_list_ccenter_ncentr_compar; /* 0025.09 */
drop procedure if exists oxpl.prc_plandoc_get_raw_ccenter_ncentr_compar; /* 0025.10 */
drop procedure if exists oxpl.prc_plandoc_get_list_ccenter_ncentr_aloc; /* 0025.11 */
drop procedure if exists oxpl.prc_plandoc_get_raw_ccenter_ncentr_aloc; /* 0025.12 */
drop procedure if exists oxpl.prc_plandoc_get_list_cdriver_centr_sumar; /* 0025.13 */
drop procedure if exists oxpl.prc_plandoc_get_raw_cdriver_centr_sumar; /* 0025.14 */
drop procedure if exists oxpl.prc_plandoc_get_list_cdriver_centr_pozitii; /* 0025.15 */
drop procedure if exists oxpl.prc_plandoc_get_raw_cdriver_centr_pozitii; /* 0025.16 */
drop procedure if exists oxpl.prc_plandoc_get_list_cdriver_centr_compar; /* 0025.17 */
drop procedure if exists oxpl.prc_plandoc_get_raw_cdriver_centr_compar; /* 0025.18 */
drop procedure if exists oxpl.prc_plandoc_get_list_cdriver_centr_aloc; /* 0025.19 */
drop procedure if exists oxpl.prc_plandoc_get_raw_cdriver_centr_aloc; /* 0025.20 */
drop procedure if exists oxpl.prc_mdl_save_alocare; /* 0026.01 */
drop procedure if exists oxpl.prc_mdl_get_alocare; /* 0026.02 */
drop procedure if exists oxpl.prc_mdl_get_sumar; /* 0026.03 */
drop procedure if exists oxpl.prc_mdl_get_alocare_by_tip; /* 0026.04 */
drop procedure if exists oxpl.prc_mdl_get_alocare_by_ccenter; /* 0026.05 */
drop procedure if exists oxpl.prc_admin_copy_dataset_vals; /* 0027.01 */
drop procedure if exists oxpl.prc_admin_delete_dataset_vals; /* 0027.02 */