drop table if exists oxpl.tbl_mdl_alocare; /* 0046 */
drop table if exists oxpl.tbl_int_ccntr_map; /* 0044 */
drop table if exists oxpl.tbl_int_recs_plan_vals; /* 0042 */
drop table if exists oxpl.tbl_int_recs_plan_head; /* 0040 */
drop table if exists oxpl.tbl_int_recs_act; /* 0038 */
drop table if exists oxpl.tbl_int_key_rule; /* 0036 */
drop table if exists oxpl.tbl_int_key_vals; /* 0034 */
drop table if exists oxpl.tbl_int_key_head; /* 0032 */
drop sequence if exists oxpl.tbl_int_key_head_sq1; /* 0031 */
drop table if exists oxpl.tbl_int_key_type; /* 0030 */
drop table if exists oxpl.tbl_int_users_cost_drivers; /* 0028 */
drop table if exists oxpl.tbl_int_users_cost_centers; /* 0026 */
drop table if exists oxpl.tbl_int_ugrup; /* 0025 */
drop table if exists oxpl.tbl_int_opex_categ_assign; /* 0022 */
drop table if exists oxpl.tbl_int_opex_categ; /* 0021 */
drop sequence if exists oxpl.tbl_int_opex_categ_sq1; /* 0020 */
drop table if exists oxpl.tbl_int_cost_driver_assign; /* 0019 */
drop table if exists oxpl.tbl_int_cost_driver; /* 0018 */
drop table if exists oxpl.tbl_int_ccntr; /* 0015 */
drop table if exists oxpl.tbl_int_ccntr_grup; /* 0014 */
drop table if exists oxpl.tbl_int_data_set_per; /* 0012 */
drop table if exists oxpl.tbl_int_data_set; /* 0010 */
drop table if exists oxpl.tbl_int_plan_vers; /* 0008 */
drop table if exists oxpl.tbl_int_month; /* 0007 */
drop table if exists oxpl.tbl_int_buss_line_asg; /* 0006 */
drop table if exists oxpl.tbl_int_buss_line; /* 0005 */
drop table if exists oxpl.tbl_int_seg_ind; /* 0004 */
drop table if exists oxpl.tbl_int_ic_part; /* 0003 */
drop table if exists oxpl.tbl_int_coarea; /* 0002 */
drop table if exists oxpl.tbl_int_backup; /* 0001 */
