enable trigger oxpl.tbl_int_plan_vers_tg1 on oxpl.tbl_int_plan_vers; /* 0009 */
enable trigger oxpl.tbl_int_data_set_tg1 on oxpl.tbl_int_data_set; /* 0011 */
enable trigger oxpl.tbl_int_data_set_per_tg1 on oxpl.tbl_int_data_set_per; /* 0013 */
enable trigger oxpl.tbl_int_ccntr_grup_tg1 on oxpl.tbl_int_ccntr_grup; /* 0016 */
enable trigger oxpl.tbl_int_ccntr_tg1 on oxpl.tbl_int_ccntr; /* 0017 */
enable trigger oxpl.tbl_int_cost_driver_assign_tg1 on oxpl.tbl_int_cost_driver_assign; /* 0023 */
enable trigger oxpl.tbl_int_opex_categ_assign_tg1 on oxpl.tbl_int_opex_categ_assign; /* 0024 */
enable trigger oxpl.tbl_int_users_cost_centers_tg1 on oxpl.tbl_int_users_cost_centers; /* 0027 */
enable trigger oxpl.tbl_int_users_cost_drivers_tg1 on oxpl.tbl_int_users_cost_drivers; /* 0029 */
enable trigger oxpl.tbl_int_key_head_tg1 on oxpl.tbl_int_key_head; /* 0033 */
enable trigger oxpl.tbl_int_key_vals_tg1 on oxpl.tbl_int_key_vals; /* 0035 */
enable trigger oxpl.tbl_int_key_rule_tg1 on oxpl.tbl_int_key_rule; /* 0037 */
enable trigger oxpl.tbl_int_recs_act_tg1 on oxpl.tbl_int_recs_act; /* 0039 */
enable trigger oxpl.tbl_int_recs_plan_head_tg1 on oxpl.tbl_int_recs_plan_head; /* 0041 */
enable trigger oxpl.tbl_int_recs_plan_vals_tg1 on oxpl.tbl_int_recs_plan_vals; /* 0043 */
enable trigger oxpl.tbl_int_ccntr_map_tg1 on oxpl.tbl_int_ccntr_map; /* 0045 */